# Numpy Array Basic Operations

In [1]:
import numpy as np

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.eye(8,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [7]:
x=np.array([[[1,2],[2,3],[4,4]]])

In [8]:
x.diagonal

<function ndarray.diagonal>

In [9]:
x

array([[[1, 2],
        [2, 3],
        [4, 4]]])

In [10]:
np.ndim(x)

3

In [11]:
x.reshape(3,2)

array([[1, 2],
       [2, 3],
       [4, 4]])

In [12]:
x

array([[[1, 2],
        [2, 3],
        [4, 4]]])

In [13]:
x.reshape(2,3)

array([[1, 2, 2],
       [3, 4, 4]])

In [14]:
x.ndim

3

In [15]:
x.diagonal()

array([[1],
       [2]])

In [16]:
np.matrix(x,dtype=None)

matrix([[1, 2],
        [2, 3],
        [4, 4]])

In [17]:
x.diagonal()

array([[1],
       [2]])

In [18]:
z=np.ones((4,4))

In [19]:
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
z[1,2]=5

In [21]:
z

array([[1., 1., 1., 1.],
       [1., 1., 5., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
z[0,1]=6

In [23]:
z

array([[1., 6., 1., 1.],
       [1., 1., 5., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
for i in range(0,4):
    for j in range(0,4):
        z[i,j]=(i+1)*(j+1)

In [25]:
z

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  4.,  6.,  8.],
       [ 3.,  6.,  9., 12.],
       [ 4.,  8., 12., 16.]])

In [26]:
z.diagonal()

array([ 1.,  4.,  9., 16.])

# Numpy to List Conversion

In [27]:
p=z.tolist()

In [28]:
p

[[1.0, 2.0, 3.0, 4.0],
 [2.0, 4.0, 6.0, 8.0],
 [3.0, 6.0, 9.0, 12.0],
 [4.0, 8.0, 12.0, 16.0]]

In [29]:
z

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  4.,  6.,  8.],
       [ 3.,  6.,  9., 12.],
       [ 4.,  8., 12., 16.]])

In [30]:
type(p)

list

In [31]:
p[1][0]

2.0

In [32]:
for i in range(0,4):
    for j in range(0,4):
        print(z[i][j])

1.0
2.0
3.0
4.0
2.0
4.0
6.0
8.0
3.0
6.0
9.0
12.0
4.0
8.0
12.0
16.0
